name: Build

"on":
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    deploy:
        runs-on: ubuntu-latest
        needs: build
        steps:
            -   uses: actions/checkout@v2

            -   id: simulate_release
                name: Simulate release
                run: echo "simulate release"