spec:
  template:
    spec:
      containers:
      - name: {{project_name|lower}}-application
        livenessProbe:
          httpGet:
            path: /health
            port: http
        readinessProbe:
          httpGet:
            path: /health
            port: http